#! /bin/bash
python mydig.py google.com   MX True  
python mydig.py youtube.com   MX True  
python mydig.py facebook.com   MX True  
python mydig.py baidu.com   MX True  
python mydig.py yahoo.com   MX True  
python mydig.py wikipedia.org   MX True  
python mydig.py google.co.in   MX True  
python mydig.py tmall.com   MX True  
python mydig.py qq.com   MX True  
python mydig.py amazon.com   MX True  
python mydig.py sohu.com   MX True  
python mydig.py google.co.jp   MX True  
python mydig.py taobao.com   MX True  
python mydig.py live.com   MX True  
python mydig.py vk.com   MX True  
python mydig.py twitter.com   MX True  
python mydig.py 360.cn   MX True  
python mydig.py linkedin.com   MX True  
python mydig.py instagram.com   MX True  
python mydig.py yahoo.co.jp   MX True  
python mydig.py sina.com.cn   MX True  
python mydig.py jd.com   MX True  
python mydig.py google.de   MX True  
python mydig.py reddit.com   MX True  
python mydig.py google.co.uk   MX True  
